import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/Provider";
import Window from "@/components/core/Window";
import { Montserrat } from 'next/font/google';

const ok = Montserrat({ subsets: ["latin"], weight: "600" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <head>
        <style>{`
          * {
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
          }

          .selectable {
            -webkit-user-select: text;
            -moz-user-select: text;
            -ms-user-select: text;
            user-select: text;
          }

          input, textarea {
            -webkit-user-select: text;
            -moz-user-select: text;
            -ms-user-select: text;
            user-select: text;
          }

          ::-webkit-scrollbar {
            display: none;
          }

          html {
            -ms-overflow-style: none;  
            scrollbar-width: none;  
          }

          body {
            overflow-y: scroll;
          }
        `}</style>
      </head>
      <body className={`${ok.className} bg-fixed bg-[#16171b]`} suppressHydrationWarning>
        <Providers>
          <Window />
          {children}
        </Providers>
      </body>
    </html>
  );
}